name: Test
on: [push, pull_request]
jobs:
  check:
    if: github.event_name != 'push' || github.ref != 'refs/heads/devel'
    runs-on: ubuntu-latest
    name: Check
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: set PYSHA
      run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: dependencies
      run: pip install -U pre-commit
    - uses: reviewdog/action-setup@v1
    - if: github.event_name != 'schedule'
      name: comment
      run: |
        if [[ $EVENT == pull_request ]]; then
          REPORTER=github-pr-review
        else
          REPORTER=github-check
        fi
        pre-commit run -a todo | reviewdog -efm="%f:%l: %m" -name=TODO -tee -reporter=$REPORTER -filter-mode nofilter
        pre-commit run -a flake8 | reviewdog -f=pep8 -name=flake8 -tee -reporter=$REPORTER -filter-mode nofilter
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT: ${{ github.event_name }}
    - run: pre-commit run -a --show-diff-on-failure
  test:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, '3.10']
    name: Test py${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -U .[dev]
    - if: startsWith(matrix.python, '3')
      run: pytest --durations-min=1
    - if: startsWith(matrix.python, '2')
      run: pytest
    - run: codecov
  matlab:
    if: github.event_name != 'pull_request' || github.head_ref != 'devel'
    runs-on: [self-hosted, python, matlab]
    name: Test matlab
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run setup-python
      run: setup-python -p3.7
    - run: pip install -U .[dev]
    - run: pytest --durations-min=1
    - run: codecov
    - name: Post Run setup-python
      run: setup-python -p3.7 -Dr
      if: ${{ always() }}
  deploy:
    needs: [check, test, matlab]
    name: PyPI Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - id: dist
      uses: casperdcl/deploy-pypi@v2
      with:
        pip: true
        gpg_key: ${{ secrets.GPG_KEY }}
        password: ${{ secrets.PYPI_TOKEN }}
        upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
    - id: meta
      name: Changelog
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD > _CHANGES.md
    - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        name: spm12 ${{ steps.meta.outputs.tag }} beta
        body_path: _CHANGES.md
        draft: true
        files: |
          dist/${{ steps.dist.outputs.whl }}
          dist/${{ steps.dist.outputs.whl_asc }}
